name: Website Deployment-matrix
on:
  push:
jobs:
  build:
    strategy:
      matrix:
        NodeJS-Version: [12, 14, 16, 20]
        os: [ubuntu-latest, macos-latest]
        include::
          - NodeJS-Version: 18
            os: macos-latest
        exclude:
          - NodeJS-Version: 14
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NOdeJS
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.NodeJS-Version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
  
