name: Website Deployment-while-on-errors
on:
  push:
jobs:
  build:
    strategy:
      matrix:
        NodeJS-Version: [12, 14, 16, 20]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NOdeJS
        uses: actions/checkout@v3
        with:
          node-version: ${{ NodeJS-Version}}
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
  